### PR TITLE
Feature/pre commit hooks scripts

### PR DESCRIPTION
**Pull request by reyoung**
Use a python package `pre-commit` to manage git `pre-commit` hooks when developing Paddle.

Git pre-commit hook is set by each developer locally. It is hard to force all developer set same `pre-commit` hooks, but there are some basic things should be check before commit, such as `python style`, `file should use \n as line end`,  etc.

This PR is added to solve this problem, by using a python package [pre-commit](http://pre-commit.com/). Each developer should do two things to enable this feature.

* Install `pre-commit` package. `pip install pre-commit`
* Enable `pre-commit` package to manage Paddle git pre-commit in local directory, by run `pre-commit install` in Paddle checkout directory.

Currently, some hooks are added, and all files are scan & fixed by this PR.

By the way, there is another thing I found about `yapf`, the python formatter used by Paddle. Different version of `yapf` could generate different result, with the same input python file. So, we must use the same `yapf` when developing Paddle. `pre-commit` also can help us to archive that.

`pre-commit` is used only by Paddle developer, we should add some other tools (or just use `pre-commit` package, I'm not sure) to complete the CI tests about these checks.

### CODE REVIEW

**Comment by luotao1** [comment]
semantic_role_labeling.md, hierarchical-layer.md, hierarchical-rnn.md，请问这三个md格式化前后有什么变化么？看上去是完全一样的。

**Comment by reyoung** [comment]
分行符，应该用\n而不是\r\n


发自 Smartisan T2

Tao Luo <notifications@github.com> 于 2016年11月14日，上午11:15写道：


semantic_role_labeling.md, hierarchical-layer.md, hierarchical-rnn.md，请问这三个md格式化前后有什么变化么？看上去是完全一样的。

―

**Comment by luotao1** [comment]
pre-commit是检测python格式的，现在还检查md么？

**Comment by reyoung** [comment]
> pre-commit是检测python格式的，现在还检查md么？

检查所有文件

**Comment by wangkuiyi** [comment]
如果要开发Paddle，需要`pip install pre-commit`安装pre-commit？

LGTM

**Pull request merged**
