### PR TITLE
fixes to build on mac os x

### PR DESCRIPTION
**Pull request by djinn**
Overall port for build process to Mac OS X. There is a problem with c++ stdlib but that is for another day.

### CODE REVIEW

**Comment by reyoung** [comment]
We will pull this code & test locally as soon as possible.

Thank you very much to patch this code.

The continuous integration sever for github is also under constructing.

**Comment by reyoung** [comment]
The std::exp not found, should include <cmath>. And there are several issues for linux tcp. If you are not hurry for fixing it, we will fix these problems in next two weeks.

**Comment by djinn** [comment]
Yes. Please fix it. I just did a preliminary check on, if it works or not. Sadly, it will be long work before it will be usable.

**Comment by kashif** [comment]
I have also extended the cmake to compile against the `Accelerate` framework... let me know if you want that snippet

**Comment by reyoung** [comment]
See #138 .

**Pull request closed without merging**
