### PR TITLE
using find_package for swig, and set version control

### PR DESCRIPTION
**Pull request by backyes**
more robust cmake for swig

* add version control while looking for swig with cmake, otherwise, some unreadable error comes.

The BUG is related with:
https://github.com/baidu/Paddle/issues/259

@reyoung Please do some code review.

@wangkuiyi You can determine if this PR should be merged into milestone 0.8.1.

### CODE REVIEW

**Comment by backyes** [comment]
@reyoung suggest using QUIET for looking for swig. Just follow his comment.

**Comment by reyoung** [comment]
Why this PR should be a bug?

We handcraft the `find swig` method. And use find(SWIG 3.0) just update the swig version from 2.X to 3.0. So, there are two things i am confused?

* find(SWIG 3.0) should be as same as we set `set(MIN_SWIG_VERSION 2)` to `set(MIN_SWIG_VERSION 3)`. Am I right for this?
* Is the Paddle using some `swig 3.0` feature that cause `swig 2.x` cannot be used?

**Comment by backyes** [comment]
有个用户场景下， 在make阶段出现了一些关于swig的异常具，体的错误并没有记录。另外， 既然cmake有swig的find_package，且能对版本控制，建议改成patch后的形式。
感觉没有必要对这些影响不大的问题，反复确认。

**Comment by reyoung** [comment]
@backyes I approve using the `find(SWIG)`. I just want to know, why you upgrade the swig 2.x to 3.0? Is there any bug before? Could you provide more details for this bug?

**Comment by reyoung** [comment]
@backyes Upgrade the dependency version will cause we lack of support some old linux distro. Like `CentOS 7`, `CentOS 6.X`. I just need to ensure these linux distro support `SWIG 3.0` if you upgrade `SWIG` version.

It is important for us.

**Comment by backyes** [comment]
OK

**Comment by reyoung** [comment]
@QiJune The default `swig` in `CentOS 7.0`, is `swig 2.0`. Is there any trouble when you build RPM package in `CentOS 7` by using `swig 2.0` ?

image

**Comment by backyes** [comment]
@reyoung   Swig 2.0  can satisfy current requirement, so use find_package(SWIG 2.0) instead.

Also rename swig.cmake->py_paddle instead, since swig.cmake will own nothing about SWIG tool except py_paddle related function.

**Comment by reyoung** [comment]
@backyes Actually, swig.cmake should not be renamed. Because in general, the `swig` part of paddle, will not just support only python, but many other language, see #258

**Comment by backyes** [comment]
@reyoung I agree with you.

**Comment by reyoung** [comment]
@backyes Sorry, the `cmake support for RDMA` PR has been check in, then make this PR conflict to develop branch. Please resolve the conflicts, and tell me to merge.

**Comment by backyes** [comment]
@reyoung conflict is removed now.

**Pull request merged**
