### PR TITLE
fixed issue when exporting python wrapper in image classification demo

### PR DESCRIPTION
**Pull request by stoneyang**

### CODE REVIEW

**Comment by emailweixu** [comment]
Did you make request because you ran into errors when running this script? Actually, the line you changed should be removed.

**Comment by stoneyang** [comment]
It is a minor one about Python environment configuration when one doesn't install the whole library on the machine. So I guess it will incur inconvenience if left unchanged or even removed.

**Comment by reyoung** [comment]
It seems that this line should be removed. It is very kind if you want to give another pull request to remove it

**Comment by reyoung** [comment]
We want user to run our demo after paddle installed. So that python library should be already add to system python after installed.

**Comment by stoneyang** [comment]
Noted. New PR will be launched assp. :)

**Comment by stoneyang** [comment]
Duh!

**Pull request merged**
