### PR TITLE
Add NOAVX Docker image scripts.

### PR DESCRIPTION
**Pull request by reyoung**
* The `Dockerfile.m4`, `build.sh`, `generate.sh` is changed file. Other file is generated by `generate.sh`
* Because docker hub need Dockerfile independently to build different image. So there is some code duplicated.

### CODE REVIEW

**Comment by reyoung** [comment]
Related to  #89

**Comment by emailweixu** [comment]
Why do you have to have same many very similar build.sh scripts? Can they be unified to a single one?

**Comment by reyoung** [comment]
@emailweixu OK, I will try to fix this.

**Comment by reyoung** [comment]
@emailweixu Put `Dockerfile` in same directory, so we can use just one `build.sh`.

To build image, use command `docker build -f Dockerfile.cpu .` to set Dockerfile explicitly.

However, the `hub.docker.com` should be updated to new path of images after this PR check in.

**Pull request merged**
